name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
           chmod +x mvnw
           ./mvnw clean package -DskipTests
      - name: Build Docker image
        run: |
          docker build -t backend .
          docker tag backend ghcr.io/akashppatel/backend
          docker push ghcr.io/akashppatel/my-spring-boot-app

#    steps:
#    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ghcr.io/akashppatel/backend:$(date +%s)
